In [1]:
import numpy as np

## THE BASICS

In [10]:
a=np.array([1,2,3],dtype="int32")
print(a)

[1 2 3]


In [11]:
b=np.array([[5.0,6.6,7.8],[3.3,3.14,3.2]])
print(b)

[[5.   6.6  7.8 ]
 [3.3  3.14 3.2 ]]


In [12]:
#for getting the dimension
a.ndim

1

In [13]:
#get shape-tells you the number of rows and columns as in total.
b.shape

(2, 3)

In [14]:
#memory the numpy array takes up-dtype,size
a.dtype

dtype('int32')

In [15]:
#Get item size
a.itemsize

4

In [16]:
#Get Total Size
a.nbytes

12

## ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS,etc

In [17]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#get specific element-array[r,c]
a[1,5]

13

In [20]:
#How to get a specific row:
# a[0,:]
a[1,:]#this means all the columns and just the specified row.

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
#How to get a specific column:
a[:,0]#this means all the rows and just the specified column.

array([1, 8])

In [29]:
#getting a little more fansy:->[startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [30]:
a[1,5]=4

In [31]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12  4 14]]


In [32]:
a[:,2]=5

In [33]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12  4 14]]


**3d-Example**

In [35]:
c=np.array([[[1,2],[2,4]],[[3,6],[4,8]],[[5,10],[6,11]]])
print(c)

[[[ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]]

 [[ 5 10]
  [ 6 11]]]


In [37]:
#Get specific element (work outside in):
c[2,0,1]

10

In [38]:
#replace
c[:,1,:]=[[2,2],[3,3],[4,4]]
print(c)

[[[ 1  2]
  [ 2  2]]

 [[ 3  6]
  [ 3  3]]

 [[ 5 10]
  [ 4  4]]]


## Initialize Different types of arrays

In [41]:
#All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
#All 1's matrix
np.ones((4,2,2),dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [47]:
#Any other number:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [53]:
#Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.15300843, 0.69002809],
       [0.49889066, 0.28835976],
       [0.45606428, 0.71982329],
       [0.35617168, 0.0169618 ]])

In [67]:
#Random integer numbers
np.random.randint(-4,6,size=(3,3))

array([[-2,  3,  2],
       [ 4,  3, -2],
       [ 2,  1,  2]])

In [71]:
#How to create an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
#How to repeat an array:
res=np.array([[1,2,3]])
res1=np.repeat(res,3,axis=0)
print(res1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [85]:
#Practice question.
d=np.ones((5,5))
print(d)
z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
d[1:4,1:4]=z
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be Careful When copying arrays!!!

In [86]:
a=np.array([1,2,3])
b=a.copy()#this should be used inorder to copy otherwise when we alter b the contents of a also gets changed as we have assigned the same variable again with a different alphabet
print(b)
print(a)
b[2]=33
print(b)
print(a)

[1 2 3]
[1 2 3]
[ 1  2 33]
[1 2 3]


### MATHEMATICS!!!

In [87]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [88]:
a+2

array([3, 4, 5, 6])

In [89]:
b=np.array([1,0,1,0])
a+b
print(a+b)

[2 2 4 4]


In [91]:
#sin and cosine:
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [93]:
x=np.ones((3,3))
print(x)
y=np.full((3,3),2)
print(y)
print(np.matmul(x,y))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [94]:
#Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [96]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [98]:
print(stats.min())#np.min(stats)

1


In [99]:
print(stats.max())#np.max(stats)

6


In [100]:
print(stats.min(axis=0))#np.min(stats,axis=0)

[1 2 3]


In [101]:
print(stats.max(axis=1))#np.max(stats,axis=1)

[3 6]


In [105]:
np.sum(stats,axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [111]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [113]:
#Vertical stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
#Horizontal stack
h1=np.array([1,2,3,4])
h2=np.array([5,6,7,8])
np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous
###### Load Data From File

In [1]:
import numpy as np
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advanced Indexing

In [13]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [16]:
#You can index the list present in the numpy array
a=np.array([1,2,3,4,5,6,7,8])
a[[1,2,7]]

array([2, 3, 8])

In [22]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [23]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [25]:
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])